site_name: LHCDataStatisticsICISE2024
repo_name: GitHub

nav:
  - Home: index.md
  - Getting started: setup.md
  - Exercises:
    - "Exercise 1": day1.md
    - "Exercise 2": day2.md
    - "Exercise 3": day3.md
    - "Exercise 4": day4.md


#theme: cosmo
#theme: united
theme: 
  name: material
  features:
    - content.code.copy
    - navigation.footer
  palette:
    primary: "deep orange"
    accent: "light orange"
    
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.details
    - pymdownx.blocks.details
    - admonition  
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
          auto_title: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true