site_name: LHCDataStatisticsICISE2024
repo_name: GitHub
repo_url: https://github.com/LHCDataStatisticsICISE2024/Website
edit_uri: edit/main/docs

nav:
  - Home: index.md

#theme: cosmo
#theme: united
theme: lumen

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.details
    - pymdownx.blocks.details
    - admonition
